name: Push trigger Build docker image to Amazon ERC

on:
  push:
    branches:
      - main

jobs:
  push-trigger-build-image:
    uses: web3art/g/.github/workflows/buildx.yaml@main
    with:
      build_env: dev
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      self_token: ${{ secrets.BOT_GITHUB_TOKEN }}
